### PR TITLE
`bitcode` coder impl

### PR DESCRIPTION
**Pull request by 0x07C0**

### CODE REVIEW

**Comment by luketpeterson** [comment]
I'm a little worried the user might not be able to encode any ValueT object format they need using bitcode.  So I want to make sure the user can pass a different Coder for the Values CF.

**Comment by luketpeterson** [comment]
These results are excellent on a larger dataset.  Here are the timings from the "cities15000" file running the lookup benchmarks:

```
bitcode

DB size = 102,622,372 bytes

lookup_exact_london        time:   [6.9620 µs 7.0958 µs 7.2518 µs]
lookup_exact_tokyo         time:   [1.6391 µs 1.6580 µs 1.6787 µs]
lookup_exact_rio           time:   [4.3231 µs 4.3655 µs 4.4109 µs]
lookup_raw_london          time:   [46.446 µs 47.011 µs 47.635 µs]
lookup_raw_tokyo           time:   [35.836 µs 36.230 µs 36.633 µs]
lookup_best_exact_london   time:   [1.7531 µs 1.7707 µs 1.7881 µs]
lookup_best_inexact_london time:   [158.73 µs 160.62 µs 162.69 µs]
lookup_fuzzy_all_london    time:   [244.34 µs 249.25 µs 254.64 µs]
lookup_fuzzy_all_tokyo     time:   [289.91 µs 293.45 µs 297.63 µs]
lookup_fuzzy_all_random    time:   [194.56 µs 197.93 µs 201.32 µs]

bincode

DB size = 115,750,448 bytes

lookup_exact_london        time:   [3.1255 µs 3.1575 µs 3.1892 µs]
lookup_exact_tokyo         time:   [3.1168 µs 3.1454 µs 3.1756 µs]
lookup_exact_rio           time:   [5.0292 µs 5.0751 µs 5.1242 µs]
lookup_raw_london          time:   [92.819 µs 94.213 µs 95.781 µs]
lookup_raw_tokyo           time:   [73.830 µs 74.749 µs 75.754 µs]
lookup_best_exact_london   time:   [3.1153 µs 3.1497 µs 3.1829 µs]
lookup_best_inexact_london time:   [192.11 µs 194.40 µs 196.82 µs]
lookup_fuzzy_all_london    time:   [276.71 µs 280.18 µs 283.94 µs]
lookup_fuzzy_all_tokyo     time:   [315.00 µs 318.73 µs 322.67 µs]
lookup_fuzzy_all_random    time:   [576.04 µs 599.02 µs 625.01 µs]
```

**Comment by caibear** [comment]
I noticed a few issues with [your implementation](https://github.com/luketpeterson/fuzzy_rocks/pull/4/files#diff-4f27812f913629ef53ea7c49b3dd3ff9b24294005576d8b38e7f57a5a9748404R167-R211 ) of decoding a single bitcode length.
1. u128 is never used and u64 is represented by 0 (not 1).
2. The [> 255](https://github.com/luketpeterson/fuzzy_rocks/pull/4/files#diff-4f27812f913629ef53ea7c49b3dd3ff9b24294005576d8b38e7f57a5a9748404R168) check isn't guaranteed since elements can encode to < 1 byte.
        For example, `vec![false, true, false, true]` encodes as `[4, 0b1010]`
3. Panics if input is too short, while the errors it does handle can't happen (try_into array will always succeed since the slice is the same length).

Here is a patched version:
```rust
fn fmt1_list_len(&self, bytes: &[u8]) -> Result<usize, String> {
    fn invalid_length() -> String {
        "invalid length".to_owned()
    }

    let first = *bytes.get(0).ok_or_else(invalid_length)?;
    if first < 255 {
        return Ok(first as usize);
    }

    // 1, 3, 5, 7 cannot occur while encoding 1 length. 6 cannot occur at all.
    match *bytes.get(1).ok_or_else(invalid_length)? {
        4 => {
            let len_chars = bytes.get(2..4).ok_or_else(invalid_length)?;
            Ok(u16::from_le_bytes(len_chars.try_into().unwrap()) as usize)
        }
        2 => {
            let len_chars = bytes.get(2..6).ok_or_else(invalid_length)?;
            Ok(u32::from_le_bytes(len_chars.try_into().unwrap()) as usize)
        }
        0 => {
            let len_chars = bytes.get(2..10).ok_or_else(invalid_length)?;
            Ok(u64::from_le_bytes(len_chars.try_into().unwrap()) as usize)
        }
        _ => Err(invalid_length()),
    }
}
```

**Comment by luketpeterson** [comment]
@caibear! The maestro! Bitcode is awesome!

Thank you for your help!

**Comment by luketpeterson** [comment]
Fix from @caibear merged in 7664082  Thanks again!

**Pull request merged**
